# Activa el servicio de ZMK Studio
CONFIG_ZMK_STUDIO=y
# Activa el servicio de monitor de batería
CONFIG_ZMK_BATTERY_REPORTING=y
# Fuerza al dongle a escuchar y promediar/reportar la batería de los periféricos
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_DISPLAY=y
